# Generated by Django 3.2.11 on 2022-01-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_type',
            new_name='gender',
        ),
    ]
