# Generated by Django 3.2.11 on 2022-01-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20220129_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='assessment',
            name='year_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
