# Generated by Django 3.2.11 on 2022-01-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20220129_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.AddField(
            model_name='studentnotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clinic.student'),
            preserve_default=False,
        ),
    ]
