# Generated by Django 3.2.11 on 2022-01-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20220129_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNotes',
            new_name='StudentNote',
        ),
    ]
