# Generated by Django 3.2.11 on 2022-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_rename_studentnotes_studentnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='notes',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='assessment',
            name='beery_percentile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='beery_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='bot_percentile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='completed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='mc_masters_percentile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='mc_masters_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='report_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='self_reg_percentile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='self_reg_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
