# Generated by Django 3.2.11 on 2022-01-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20220130_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='beery_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='beery_score',
            field=models.CharField(blank=True, choices=[('average', 'Average'), ('below average', 'Below Average'), ('well below average', 'Well Below Average')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='bot_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='bot_score',
            field=models.CharField(blank=True, choices=[('average', 'Average'), ('below average', 'Below Average'), ('well below average', 'Well Below Average')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mc_masters_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mc_masters_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='self_reg_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
